### ISSUE TITLE
SyntaxError: Named export 'extractByIndices' not found. The requested module '@untemps/utils/array/extractByIndices' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by ziedHamdi** [untemps/svelte-palette#69]
Hi Vincent,

Thanks for the great lib, it saved me a few days of work.

I have [this error](https://github.com/orgs/vercel/discussions/2526) when automatically deploying on Vercel (through git push). I don't have issues when compiling locally, I'm not sure about the cause of it as I can't reproduce it, and I can't access the generated files by Vercel. So I thought, you might have some ideas:

import { extractByIndices } from "@untemps/utils/array/extractByIndices";
^^^^^^^^^^^^^^^^
SyntaxError: Named export 'extractByIndices' not found. The requested module '@untemps/utils/array/extractByIndices' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@untemps/utils/array/extractByIndices';
const { extractByIndices } = pkg;

at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

**Comment by ziedHamdi** [comment]
This SO thread might help:

https://stackoverflow.com/questions/70605320/named-export-types-not-found-the-requested-module-mongoose-is-a-commonjs-mo

**Comment by untemps** [comment]
Hi Zied,
Thanks for your report.
Any clue about the version of Node installed on the Vercel server?

**Comment by ziedHamdi** [comment]
Hi Vincent,

My Vercel is set to use 18.x
![screenshot-vercel com-2023 06 08-08_40_05](https://github.com/untemps/svelte-palette/assets/7271508/07f09850-8874-455d-89bb-a889f36f930b)

**Comment by untemps** [comment]
You may have the issue if you build your project locally with `vite build`.
I guess the `untemps/utils` is missing from the package. I should add it to the exported filed or reference it as peer dependency.

In the meantime, installing `@untemps/utils` in your project should do the trick. Please let me know if it doesn't.

**Comment by ziedHamdi** [comment]
Great! It works back on Vercel. That's weird, they didn't resolve the dependency?
